### ISSUE TITLE
Deprecation warning when using FontAwesome glyphs

### ISSUE THREAD

**Issue by jemus42** [hrbrmstr/waffle#17]
`1: `show_guide` has been deprecated. Please use `show.legend` instead.`

…I know this package is mainly a joke, but I *actually use it as a pie chart alternative*.

;__;

**Comment by hrbrmstr** [comment]
it is actually not a joke pkg (i and others use it for visual proportion communication as well). the warning hasn't been bad for me but I'll update and get it in CRAN in short order. thx.

**Comment by hrbrmstr** [comment]
fixed in 0.5.1 (just now).
