### ISSUE TITLE
Problem, when a zero in the data is included: Is there a workaround?

### ISSUE THREAD

**Issue by cutterkom** [hrbrmstr/waffle#20]
I am using waffle in a for looping over a dataframe and generating multiple plots.

An example from my data:
`1	99`
`85	15`
`8	92`
`1	99`
`10	90`
`0	100`

The problem is the last set of numbers: When there is a 0 included, waffle behaves like it's a 100. The zero seems to be ignored. Is there a way to prevent this?

Working: Green = 10, orange = 90
`waffle(c(10, 90))`

Not working: Green = 0
`waffle(c(0, 100))`

![image](https://cloud.githubusercontent.com/assets/4574033/14632525/7ff94008-0619-11e6-9aff-976d232b2a77.png)

![image](https://cloud.githubusercontent.com/assets/4574033/14632517/77879f46-0619-11e6-8da1-050f1b592fc1.png)

**Comment by zx8754** [comment]
Relevant post at [SO](http://stackoverflow.com/questions/36738505)

**Comment by brudis-r7** [comment]
```
gridExtra::grid.arrange(
  waffle(c(thing1=0, thing2=100), rows=5),  
  waffle(c(thing1=25, thing2=75), rows=5)
)
```
![image](https://cloud.githubusercontent.com/assets/16005804/14677350/4d6ff5d4-06df-11e6-96cb-8d472ffbd006.png)

**Comment by brudis-r7** [comment]
i did not notice locally that i was still in the CRAN branch.

i'll move it over to master when i get a chance. apologies.
