### ISSUE TITLE
Inconsistent legend labelling

### ISSUE THREAD

**Issue by puterleat** [hrbrmstr/waffle#23]
I think this is a problem:

```
waffle(c(`a`=0, `b`=20, `c`=20), rows=5, pad=1,
       colors=c("red", '#cccccc', "#969696"))

waffle(c(`a`=10, `b`=20, `c`=20), rows=5, pad=1,
       colors=c("red", '#cccccc', "#969696"))

```

In the first plot the legend is labelled with a and b, even though there are no a's. Note in plot 1 B's appear in red. In the second plot A's appear in red.

**Comment by hrbrmstr** [comment]
actually, they don't if you're using the github devel version of waffle
