### ISSUE TITLE
"panel.spacing" is not a valid theme element name.

### ISSUE THREAD

**Issue by Trybnetic** [hrbrmstr/waffle#31]
I just tried to use your package on Linux (Ubuntu 16.04) and R Version 3.3.2 and unfortunately I got an error while I was trying to plot the waffle plot from the example.

Here is the log of my console, hopefully this can help you to fix it

```r
> library(waffle)
> 
> # current verison
> packageVersion("waffle")
[1] ‘0.7.0’
> ## [1] '0.7.0'
> 
> # basic example
> parts <- c(80, 30, 20, 10)
> waffle(parts, rows=8)
Error in (function (el, elname)  : 
  "panel.spacing" is not a valid theme element name.
```

Let me know if you need further informations or probably know the reason for this error.

**Comment by hrbrmstr** [comment]
Upgrade ggplot2.

**Comment by Trybnetic** [comment]
Thanks a lot for the fast support! 
Works great!
