### ISSUE TITLE
`iron()` doesn't return a ggplot object

### ISSUE THREAD

**Issue by andrewheiss** [hrbrmstr/waffle#54]
It might be helpful to allow users to save the output of `iron()` as an object for later use with `ggsave()`, patchwork, gridExtra, etc. Plots created with `waffle()` are returned as `gg`/`ggplot` objects, but the output of `iron()` is currently `NULL`.

Here's a reprex:

``` r
library(tidyverse)
library(waffle)

iron(
  waffle(c(thing1 = 0, thing2 = 100), rows = 5),
  waffle(c(thing1 = 25, thing2 = 75), rows = 5)
)
```

![](https://i.imgur.com/5mto4fu.png)

``` r
# Try to save this as an object
ironed_plot <- iron(
  waffle(c(thing1 = 0, thing2 = 100), rows = 5),
  waffle(c(thing1 = 25, thing2 = 75), rows = 5)
)

# There's immediate output...
# And the object is null, so we can't use it with ggsave()
ironed_plot
#> NULL

# This is the only way to get this to work with iron()
ggsave(last_plot(), filename = "ironed.pdf")
#> Saving 7 x 5 in image
```

We can work around this issue right now with patchwork or gridExtra by saving the individual waffle plot as objects and then not using `iron()`, but then the margins between the waffles are too big.

```r
# Semi workaround with patchwork, but between-margins are too big
library(patchwork)

plot1 <- waffle(c(thing1 = 0, thing2 = 100), rows = 5)
plot2 <- waffle(c(thing1 = 25, thing2 = 75), rows = 5)

ironed_plot_patchwork <- plot1 + plot2 +
  plot_layout(ncol = 1)

ironed_plot_patchwork
```

![](https://i.imgur.com/nuwpini.png)

``` r
# This works now
ggsave(ironed_plot_patchwork, filename = "ironed_patchwork.pdf")
#> Saving 7 x 5 in image
```

**Comment by andrewheiss** [comment]
Actually, update here: `last_plot()` doesn't work.

However, wrapping `iron()` in an old-fashioned `pdf() ... dev.off()` does work:

```r
library(tidyverse)
library(waffle)

png("ironed.png")
iron(
  waffle(c(thing1 = 0, thing2 = 100), rows = 5),
  waffle(c(thing1 = 25, thing2 = 75), rows = 5)
)
invisible(dev.off())


png("ironed.pdf")
iron(
  waffle(c(thing1 = 0, thing2 = 100), rows = 5),
  waffle(c(thing1 = 25, thing2 = 75), rows = 5)
)
invisible(dev.off())
```

**Comment by hrbrmstr** [comment]
I think `patchwork` or `cowplot` are likely better alternatives at this point tho (or `geom_waffle()`)

**Comment by cherz4** [comment]
I completely agree with OP - is there a way to make iron() return with gg or ggplot type?  Cowplot's plot_grid doesn't take the iron() output nor does patchwork seem too.
